include: "rules/3. cojo.smk"

rule run:
    input:
        f"output/{COHORT}/{GROUP}/{PHENOTYPE}/manqq/manqq.{config['manqq']['maf_filter']}.qq.png",
        f"output/{COHORT}/{GROUP}/{PHENOTYPE}/peaks/.done",
        f"output/{COHORT}/{GROUP}/{PHENOTYPE}/all.cojo.jma.csv.gz"

