container:
  all: "https://github.com/hmgu-itg/single-point-analysis-pipeline/releases/download/0.0.1/hmgu-itg-single-point-analysis-pipeline.latest.sif"
  manqq: "library://hmgu-itg/default/manqq:0.2.3"
  peakplotter: "library://hmgu-itg/default/peakplotter:0.4.3"

# Cohort name
cohort: ""

# Path to cohort's plink bfile prefix
bfile: ""

# Path to cohort's genetic relatedness matrix
grm: ""

# Group name
group: ""

# Phenotype name
phenotype: ""

# Path to phenotype file
phenotype_file: ""

manqq:
  maf_filter: 0.001

peakplotter:
  span: 1000000

QC_thresholds:
  MAC: 10
  HWE: 1e-5
  missingness: 0.01
  p-value: 5e-8
