## Run options
run:
  manqq: true
  peakplotter: true

## Input values
# You can hard code the values here
# or provide these values via the commandline
# as suggested in the README.

# Path to cohort's plink bfile prefix
bfile: ""

# Path to cohort's plink .lmiss file
lmiss: ""

# Path to cohort's genetic relatedness matrix
grm: ""

# Path to phenotype file
phenotype_file: ""

# Significance threshold
p-value: !!float 5e-8

# MAF filter to apply before generating the QQ-plot
manqq:
  maf_filter: !!float 0.001

# PeakPlotter peak width.
# 1Mb here means the minimum peak window will be 2Mb (1Mb up and downstream)
peakplotter:
  span: 1000000
  vep_ld: 0.0

## Predefined containers
# Do not change unless you know what you're doing 
container:
  all: "https://github.com/hmgu-itg/single-point-analysis-pipeline/releases/download/0.0.1/hmgu-itg-single-point-analysis-pipeline.latest.sif"
  manqq: "library://hmgu-itg/default/manqq:0.2.4"
  peakplotter: "library://hmgu-itg/default/peakplotter:0.7.0"
